# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install Pipenv and Cookiecutter
        run: |
          python -m pip install --upgrade pip
          pip install pipenv cookiecutter
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 3.6
      - name: Create Project
        run: cookiecutter . --no-input
      - name: Run Tests
        run: |
          cd demo-project
          pipenv run pytest -s -vv
