name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install Poetry and Cookiecutter
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install poetry cookiecutter
      - name: Test Server Code
        run: sudo make test-server-code
      - name: Test Docker Compose
        run: sudo make test-docker-compose
